language: ruby
rvm:
 - "2.2.3"

before_script:
  - npm install

script:
  - bundle exec rspec spec
  - npm test
  - bundle exec rubocop
  - npm run lint

addons:
  code_climate:
    repo_token: 9e26473dfca36dbdab8081c7b6fc32b00fadd846b1bb5cd4457bfad10cf2472d
