language: ruby
rvm:
 - "2.2.3"

services:
  - mongodb
  - redis-server

env:
  - TRAVIS_NODE_VERSION="5.0.0"

install:
  - wget -P /tmp http://nodejs.org/dist/v$TRAVIS_NODE_VERSION/node-v$TRAVIS_NODE_VERSION-linux-x64.tar.xz
  - mkdir ~/nodejs
  - tar -C ~/nodejs --strip-components 1 -xf /tmp/node-v$TRAVIS_NODE_VERSION-linux-x64.tar.xz
  - export PATH=~/nodejs/bin:$PATH
  - which node
  - node --version
  - npm install
  - bundle install --deployment --path=${BUNDLE_PATH:-vendor/bundle}

script:
  - bundle exec rspec spec
  - npm test
  - bundle exec rubocop
  - npm run lint

addons:
  code_climate:
    repo_token: 9e26473dfca36dbdab8081c7b6fc32b00fadd846b1bb5cd4457bfad10cf2472d
