language: ruby
rvm:
 - "2.2.3"

env:
  - TRAVIS_NODE_VERSION="5"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - mv node_modules npm
  - npm/.bin/npm --version
  - npm/.bin/npm install

script:
  - bundle exec rspec spec
  - npm test
  - bundle exec rubocop
  - npm run lint

addons:
  code_climate:
    repo_token: 9e26473dfca36dbdab8081c7b6fc32b00fadd846b1bb5cd4457bfad10cf2472d
