default_hosts: &default_host
  hosts:
    - localhost:27017

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>

development:
  clients:
    default:
      database: cloudnet_api_dev
      <<: *default_host

test:
  clients:
    default:
      database: cloudnet_api_test
      <<: *default_host
