default_hosts: &default_host
  hosts:
    - localhost:27017

production:
  uri: <%= ENV['MONGODB_URI'] %>
  sessions:
    default:
      database: cloudnet_api

development:
  sessions:
    default:
      database: cloudnet_api_dev
      <<: *default_host

test:
  sessions:
    default:
      database: cloudnet_api_test
      <<: *default_host
