#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development: &development_defaults
  key:    1234567890ABCDEF1234567890ABCDEF
  iv:     1234567890ABCDEF
  cipher_name: aes-128-cbc

test:
  <<: *development_defaults

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  #
  # Sample RSA Key, DO NOT use this RSA key, generate a new one using
  #    openssl genrsa 2048
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAnS6Hyz8KwziCz1Zv9SRvztlWLmJQZe2CuBRp7jz9bIYwEiqF
    r7opnuu1R8/GWlOgPpCz8+RZwfnCVj4QxV+51Kd0X4OgvIhSVzqevjd9R7ArqX0m
    vKpwYTTrK3zTrInhGpA8/xZs+6lZDDFkiMpLRrUUYKGY4QbK4BequvQzwYcpW3lT
    cfuxNDeO4NQQgoNSbBkePOCusIUP7g1x8tGx27Pz9B/JiSwJIaKfuQdWu8GOFwhp
    BSCR+99OSS9CLi2k+mfbXmMh8vbvEd6ZgIF0IH/4kzJfd5ES+U+tY0VtSj+9NaI4
    CCq1nZ6KMfoBGZ9Oqr5wjLw7aqL2KRnDGrSxUQIDAQABAoIBAHDHRRnY5vEB6CG6
    ZGRhO3QQTxzC3+ryittnkkYlLrSiZ3VxWzCmA10KxKx88VY4MH8Ttnqlep2Khhz5
    NXFY6O4jJIWv3THJIkOCRQo4qEQ6rGlU6elu5Wlp3d77Fqny2DgGDC3/Oj0r2j+8
    ZOUdOPvHy5I2AIpdJE27zX2M4GHXaDxtZVhfX7rr+kWvffR0CAivSwpV38Z22cuQ
    WR3ipPSwNYV1zOEE9FQdr5zRuPvZ4LcJVlTw+3ARK9DvSbqoec/eiTazLbY4k1UD
    gLBI388aXr5ZKEIWcfA1LjoBbDLRrVWe2bLuDC9UHczPj08c+86gkgthwUBI8h4C
    0CxA5h0CgYEAyxfzGD5YbI/pQ5l1RhhuA3/FXm0b8oAHBAcRV9bQu1aWwfoLOidi
    LHrsGlaYzOxuW9KtWIA6c4a+Vq38C0wB6al+MXZLGON1BfR0A0NamZrAm1HQ4zYh
    U+QV/cfskNFny0/EtMQCkM9WfzmE5khKbHC9Xk+sr6ItqIqLGkKTej8CgYEAxiDI
    JQ5ikFzhWEPRCFYdO3kHfqAcZWhtc4pKv/ViYaBSrsvsUKv/ocAqDX2lLqkvHtDI
    HTrNaVBywVakMW8mudmGteHoPpRsuA9Zfm7LOmej8sqOtOJfWpz1RcFcK47M6gu7
    1sfV8Se3V50UufZ0H2TG2nVEZPMiQCaZ8x+xUG8CgYA4yaCSldQ5vt+1pDIzgF86
    oT550b5vxzau/J7v1cQVrfeHk7gR8bM0xsY/8xjUrAOLr1QDHA+7/+A28n04V29t
    e5Qqlm4XLnqpSJor02iA7NGQXIcxERCumWdAx+cw8yy3n71b4jbpcOA5wMaVcX9F
    5Rw+Q78AeTOVHfAZTqZYFwKBgDBrMn5b1ZqSGEAJ0rvGz74JBdvcJRRjQNxLn5jp
    zvEszQgKreXJIt/UpnJFkmikz+8n9r+t7yUdk+3LzrSGBWDF2DX6z1b7ztXsamKL
    kP7k9RwQhG+QIt1yHj690liSvWE1HOKQU6hrnFK9AKOxpw9FAZPBtMU25dfnlxfj
    VuHhAoGBAIMJTqQgMuR5a6HDhhBpsYI2llShujhXoZMQ84+HhoYI5QmcrOwm/w5X
    wKWmJu588uauptmaIhCVWaNK8hsekvSPmhV2MUSX4InpMYb53E+codVMCcPUCLuW
    yhErRaVGTEt98hb9Qb4Bm3ltLzn4hL/alFxttse1TTfr9NjePttE
    -----END RSA PRIVATE KEY-----

  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Symmetric Encryption Key encrypted using the RSA public key derived from the private key
      encrypted_key: "<%= ENV['SYMMETRIC_ENCRYPTION_KEY'] %>"
      iv_key:        "<%= ENV['SYMMETRIC_ENCRYPTION_IV'] %>"
      cipher_name:   aes-256-cbc
